import os

Z_API_INSTANCE = "3E84D96FA64D02171F6692EB59F3FBA2"
Z_API_TOKEN = "34D8B9D16CCB6070EF5D38CB"
Z_API_BASE_URL = f"https://api.z-api.io/instances/{Z_API_INSTANCE}/token/{Z_API_TOKEN}"

SUBSCRIPTION_PRICE = 47.00

AI_INTEGRATIONS_OPENAI_API_KEY = os.environ.get("AI_INTEGRATIONS_OPENAI_API_KEY")
AI_INTEGRATIONS_OPENAI_BASE_URL = os.environ.get("AI_INTEGRATIONS_OPENAI_BASE_URL")
